-- MySQL Script generated by MySQL Workbench
-- Thu Feb 20 17:03:41 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `id_usuarios` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `Contraseña` VARCHAR(45) NULL,
  `Documento` INT NOT NULL,
  `Estado` TINYBLOB NULL,
  `Telefono` INT NULL,
  `Rol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contratista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contratista` (
  `id_Contratista` INT NOT NULL,
  `Tipo_de_contrato` VARCHAR(45) NULL,
  `Fecha_Inicio` VARCHAR(45) NULL,
  `Fecha_Fin` VARCHAR(45) NULL,
  `Usuarios_id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_Contratista`),
  INDEX `fk_Contratista_Usuarios1_idx` (`Usuarios_id_usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Contratista_Usuarios1`
    FOREIGN KEY (`Usuarios_id_usuarios`)
    REFERENCES `mydb`.`Usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gestion Documental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gestion Documental` (
  `id_Gestion Documento` INT NOT NULL,
  `Tipo_Ducumento` VARCHAR(45) NULL,
  `url_Archivo` VARCHAR(45) NULL,
  `Estado_Validacion` VARCHAR(45) NULL,
  `Estado de revision` TINYBLOB NULL,
  `observaciones` VARCHAR(45) NULL,
  `Clasificacion` VARCHAR(45) NULL,
  `Fecha_De_Revision` VARCHAR(45) NULL,
  `Contratista_id_Contratista` INT NOT NULL,
  `Usuarios_id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_Gestion Documento`),
  INDEX `fk_Gestion Documental_Contratista1_idx` (`Contratista_id_Contratista` ASC) VISIBLE,
  INDEX `fk_Gestion Documental_Usuarios1_idx` (`Usuarios_id_usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Gestion Documental_Contratista1`
    FOREIGN KEY (`Contratista_id_Contratista`)
    REFERENCES `mydb`.`Contratista` (`id_Contratista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gestion Documental_Usuarios1`
    FOREIGN KEY (`Usuarios_id_usuarios`)
    REFERENCES `mydb`.`Usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cuentas de Cobro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cuentas de Cobro` (
  `id_Cuenta` INT NOT NULL,
  `Monto` VARCHAR(45) NULL,
  `Estado_De_La_Cuenta` VARCHAR(45) NULL,
  `Fecha_Creacion` VARCHAR(45) NULL,
  `Fecha_Final_De_Revision` VARCHAR(45) NULL,
  `Fecha_de_aprabacion` VARCHAR(45) NULL,
  `Gestion Documental_id_Gestion Documento` INT NOT NULL,
  `Usuarios_id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_Cuenta`),
  INDEX `fk_Cuentas de Cobro_Gestion Documental1_idx` (`Gestion Documental_id_Gestion Documento` ASC) VISIBLE,
  INDEX `fk_Cuentas de Cobro_Usuarios1_idx` (`Usuarios_id_usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Cuentas de Cobro_Gestion Documental1`
    FOREIGN KEY (`Gestion Documental_id_Gestion Documento`)
    REFERENCES `mydb`.`Gestion Documental` (`id_Gestion Documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cuentas de Cobro_Usuarios1`
    FOREIGN KEY (`Usuarios_id_usuarios`)
    REFERENCES `mydb`.`Usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reportes` (
  `idReporte` INT NOT NULL,
  `id_usuarios` VARCHAR(45) NULL,
  `tipo_reporte` VARCHAR(45) NULL,
  `fecha_generacion` VARCHAR(45) NULL,
  `Usuarios_id_usuarios` INT NOT NULL,
  PRIMARY KEY (`idReporte`),
  INDEX `fk_Reportes_Usuarios1_idx` (`Usuarios_id_usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Reportes_Usuarios1`
    FOREIGN KEY (`Usuarios_id_usuarios`)
    REFERENCES `mydb`.`Usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
